# Manage Jenkins >> Credentials
credentials:

  # System (Store)
  system:
    domainCredentials:

    # Global credentials (unrestricted)
    - credentials:
      - vaultAppRoleCredential:
          id: "vault-role-jenkins"
          path: "approle"
          roleId: "${CASC_VAULT_APPROLE}"
          scope: GLOBAL
          secretId: "${CASC_VAULT_APPROLE_SECRET}"
          usePolicies: false

      - vaultStringCredentialImpl:
          engineVersion: "1"
          id: "vault-kv1-secret"
          path: "kv1/jenkins/secret-text"
          scope: GLOBAL
          vaultKey: "secret"

      - vaultStringCredentialImpl:
          engineVersion: "2"
          id: "vault-kv2-secret"
          path: "v1/kv2/data/jenkins/secret-text"
          scope: GLOBAL
          vaultKey: "secret"

      - string:
          description: "1Password Service Account Authorization Token"
          id: "op-service-account-token"
          scope: GLOBAL
          secret: "${OP_SERVICE_ACCOUNT_TOKEN}"
