# Manage Jenkins >> Credentials
credentials:

  # System (Store)
  system:
    domainCredentials:

    # Global credentials (unrestricted)
    - credentials:
      - vaultAppRoleCredential:
          id: "vault-role-jenkins"
          path: "approle"
          roleId: "${CASC_VAULT_APPROLE}"
          scope: GLOBAL
          secretId: "${CASC_VAULT_APPROLE_SECRET}"
          usePolicies: false

      - vaultStringCredentialImpl:
          engineVersion: "${CASC_VAULT_ENGINE_VERSION}"
          id: "vault-secret-text"
          path: "kv/jenkins/secret-text"
          scope: GLOBAL
          vaultKey: "secret"

      - string:
          description: "Secret passed in from Vault as a secret source for JCasC"
          id: "vault-source-secret-text"
          scope: GLOBAL
          secret: "${kv/jenkins/secret-text/secret}"
