# Manage Jenkins >> Credentials
credentials:

  system:
    domainCredentials:
    - credentials:
      - vaultAppRoleCredential:
          id: "vault-jenkins-role"
          path: "approle"
          roleId: "${CASC_VAULT_APPROLE}"
          scope: GLOBAL
          secretId: "${CASC_VAULT_APPROLE_SECRET}"
          usePolicies: false

      - vaultStringCredentialImpl:
          engineVersion: "${CASC_VAULT_ENGINE_VERSION}"
          id: "vault-secret-text"
          path: "secrets/creds/secret-text"
          scope: GLOBAL
          vaultKey: "secret"
