# Manage Jenkins >> Credentials
credentials:

  # System (Store)
  system:
    domainCredentials:

    # Global credentials (unrestricted)
    - credentials:
      - string:
          description: "1Password Service Account Authorization Token"
          id: "op-service-account-token"
          scope: GLOBAL
          secret: "${OP_SERVICE_ACCOUNT_TOKEN}"
