# Jobs (AKA Projects)
# If pulling from GitHub, must use raw file links
# If using script code, script code is Groovy, not YAML
jobs:
  - file: 'C:\\Users\\Jhenna-Rae.Foronda-C\\GitHub\\jenkins-test\\configs\\job_dsl\\seedJobs.groovy'
