# Manage Jenkins >> Credentials Providers
globalCredentialsConfiguration:
  configuration:

    # Providers
    providerFilter:
      includes:
        classNames:
        - "com.cloudbees.hudson.plugins.folder.properties.FolderCredentialsProvider"
        - "com.cloudbees.plugins.credentials.SystemCredentialsProvider$ProviderImpl"

    # Types
    typeFilter:
      includes:
        classNames:
        - "org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl" # Secret text
