# Manage Jenkins >> Security
jenkins:

  agentProtocols:
  - "JNLP4-connect"
  - "Ping"

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

  disableRememberMe: false

  markupFormatter: "plainText"

  securityRealm:
    mock:
      data: |-
        admin FullAdmin
        bob JobAdmin
        bill JobAdmin
        tim JobManager
        tom JobManager
        auto ServiceUser
        jane User
        john User
      groupIdStrategy: "caseInsensitive"
      randomDelay: false
      userIdStrategy: "caseInsensitive"

  slaveAgentPort: -1


security:

  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true

  gitHooks:
    allowedOnAgents: false
    allowedOnController: false

  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"

  globalJobDslSecurityConfiguration:
    useScriptSecurity: true

  queueItemAuthenticator:
    authenticators:
    - global:
        strategy:
          specificUsersAuthorizationStrategy:
            userid: "auto"
