# Manage Jenkins >> Security
jenkins:

  agentProtocols:
  - "JNLP4-connect"
  - "Ping"

  authorizationStrategy:
    roleBased:
      roles:
        global:
        - entries:
          - group: "FullAdmin"
          name: "FullAdmin"
          pattern: ".*"
          permissions:
          - "Overall/Administer"

        - entries:
          - group: "JobAdmin"
          name: "JobAdmin"
          pattern: ".*"
          permissions:
          - "Agent/Connect"
          - "Agent/Disconnect"
          - "Agent/ExtendedRead"
          - "Credentials/View"
          - "Job/Build"
          - "Job/Cancel"
          - "Job/Configure"
          - "Job/Discover"
          - "Job/ExtendedRead"
          - "Job/Read"
          - "Job/Workspace"
          - "Metrics/HealthCheck"
          - "Metrics/ThreadDump"
          - "Metrics/View"
          - "Overall/Read"
          - "Overall/SystemRead"
          - "Run/Replay"
          - "View/Read"

        - entries:
          - group: "JobManager"
          name: "JobManager"
          pattern: ".*"
          permissions:
          - "Job/Build"
          - "Job/Cancel"
          - "Job/Discover"
          - "Job/Read"
          - "Overall/Read"
          - "View/Read"

        - entries:
          - group: "ServiceUser"
          name: "ServiceUser"
          pattern: ".*"
          permissions:
          - "Job/Build"
          - "Job/Cancel"
          - "Job/Read"
          - "Overall/Read"

        - name: "User"
          pattern: ".*"
          permissions:
          - "Job/Read"
          - "Overall/Read"
          - "View/Read"

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

  disableRememberMe: false

  markupFormatter: "plainText"

  securityRealm:
    mock:
      data: |-
        admin FullAdmin
        bob JobAdmin
        bill JobAdmin
        tim JobManager
        tom JobManager
        auto ServiceUser
        jane User
        john User
      groupIdStrategy: "caseInsensitive"
      randomDelay: false
      userIdStrategy: "caseInsensitive"

  slaveAgentPort: -1


security:

  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true

  gitHooks:
    allowedOnAgents: false
    allowedOnController: false

  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"

  globalJobDslSecurityConfiguration:
    useScriptSecurity: true

  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: "triggeringUsersAuthorizationStrategy"
