# Manage Jenkins >> Security
jenkins:

  agentProtocols:
  - "JNLP4-connect"
  - "Ping"

  authorizationStrategy:
      roleBased:
        roles:
          global:
          - entries:
            - group: "FullAdmin"
            name: "FullAdmin"
            pattern: ".*"
            permissions:
            - "Overall/Administer"

          - entries:
            - group: "JobAdmin"
            name: "JobAdmin"
            pattern: ".*"
            permissions:
            - "Job/Move"
            - "Job/Build"
            - "View/Create"
            - "Job/Read"
            - "Overall/SystemRead"
            - "Job/Delete"
            - "View/Configure"
            - "Metrics/HealthCheck"
            - "Metrics/ThreadDump"
            - "SCM/Tag"
            - "Job/Create"
            - "Job/Discover"
            - "Agent/ExtendedRead"
            - "Credentials/View"
            - "Agent/Connect"
            - "Run/Replay"
            - "Agent/Disconnect"
            - "Run/Delete"
            - "Job/Cancel"
            - "Overall/Read"
            - "Run/Update"
            - "View/Delete"
            - "Job/Configure"
            - "Metrics/View"
            - "Job/Workspace"
            - "View/Read"

          - entries:
            - group: "JobManager"
            name: "JobManager"
            pattern: ".*"
            permissions:
            - "Job/Cancel"
            - "Overall/Read"
            - "Job/Build"
            - "Job/Discover"
            - "Job/Read"
            - "View/Read"

          - name: "User"
            pattern: ".*"
            permissions:
            - "Overall/Read"
            - "Job/Read"
            - "View/Read"

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

  disableRememberMe: false

  markupFormatter: "plainText"
  
  securityRealm:
    mock:
      data: |-
        admin FullAdmin
        bob JobAdmin
        bill JobAdmin
        tim JobManager
        tom JobManager
        jane User
        john User
      groupIdStrategy: "caseInsensitive"
      randomDelay: false
      userIdStrategy: "caseInsensitive"

  slaveAgentPort: -1


security:

  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true

  gitHooks:
    allowedOnAgents: false
    allowedOnController: false

  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"

  globalJobDslSecurityConfiguration:
    useScriptSecurity: true

  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: "triggeringUsersAuthorizationStrategy"
