# Manage Jenkins >> System
# Do not add "remotingSecurity" section as per https://www.jenkins.io/doc/book/security/controller-isolation/jep-235/#api-compatibility
jenkins:

  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"

  # Labels
  labelAtoms:
  - name: "built-in"

  mode: NORMAL

  noUsageStatistics: true
  
  numExecutors: 2

  projectNamingStrategy:
    roleBased:
      forceExistingJobs: false

  quietPeriod: 5

  scmCheckoutRetryCount: 0


unclassified:

  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"

  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"

  globalLibraries:
    libraries:
    - defaultVersion: "main"
      name: "utils"
      retriever:
        modernSCM:
          libraryPath: "shared_libraries/utils/"
          scm:
            git:
              id: "6fc87cf5-d8df-492e-9773-786c0e84c7c7"
              remote: "https://github.com/Minreaux/jenkins-test"
              traits:
              - sparseCheckoutPaths:
                  extension:
                    sparseCheckoutPaths:
                    - path: "shared_libraries/utils/"

  hashicorpVault:
    configuration:
      disableChildPoliciesOverride: false
      engineVersion: "${CASC_VAULT_ENGINE_VERSION}"
      skipSslVerification: true
      timeout: 60
      vaultCredentialId: "vault-jenkins-role"
      vaultUrl: "${CASC_VAULT_URL}"

  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://localhost:8080/"

  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false

  pollSCM:
    pollingThreadCount: 10

  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
