# Manage Jenkins >> System
jenkins:

  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"

  labelAtoms:
  - name: "built-in"

  mode: NORMAL

  myViewsTabBar: "standard"

  numExecutors: 2
  
  primaryView:
    all:
      name: "all"

  projectNamingStrategy:
    roleBased:
      forceExistingJobs: false

  quietPeriod: 5

  scmCheckoutRetryCount: 0

  views:
  - all:
      name: "all"

  viewsTabBar: "standard"


unclassified:

  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"

  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"

  globalLibraries:
    libraries:
    - defaultVersion: "main"
      name: "utils"
      retriever:
        modernSCM:
          libraryPath: "shared_libraries/utils/"
          scm:
            git:
              id: "6fc87cf5-d8df-492e-9773-786c0e84c7c7"
              remote: "https://github.com/Minreaux/jenkins-test"
              traits:
              - sparseCheckoutPaths:
                  extension:
                    sparseCheckoutPaths:
                    - path: "shared_libraries/utils/"

  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://localhost:8080/"

  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false

  pollSCM:
    pollingThreadCount: 10

  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
