# Views
jenkins:

  myViewsTabBar: "standard"
  viewsTabBar: "standard"

  views:
  - all:
      name: "all"

  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      description: "Lists all jobs other than seedJobs."
      filterQueue: true
      includeRegex: "(?!^seedJobs$)(^.*$)"
      name: "Normal Jobs"
