credentials:
  system:
    domainCredentials:
    - credentials:
      - vaultAppRoleCredential:
          id: "vault-jenkins-role"
          path: "approle"
          roleId: "${CASC_VAULT_APPROLE}"
          scope: GLOBAL
          secretId: "${CASC_VAULT_APPROLE_SECRET}"
          usePolicies: false
      - vaultStringCredentialImpl:
          engineVersion: "${CASC_VAULT_ENGINE_VERSION}"
          id: "vault-secret-text"
          path: "secrets/creds/secret-text"
          scope: GLOBAL
          vaultKey: "secret"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - entries:
          - group: "FullAdmin"
          name: "FullAdmin"
          pattern: ".*"
          permissions:
          - "Overall/Administer"
        - entries:
          - group: "JobAdmin"
          name: "JobAdmin"
          pattern: ".*"
          permissions:
          - "Metrics/ThreadDump"
          - "Job/Build"
          - "Job/Discover"
          - "Job/Read"
          - "Agent/ExtendedRead"
          - "Credentials/View"
          - "Agent/Connect"
          - "Run/Replay"
          - "Agent/Disconnect"
          - "Job/Cancel"
          - "Job/ExtendedRead"
          - "Overall/Read"
          - "Overall/SystemRead"
          - "Job/Configure"
          - "Job/Workspace"
          - "Metrics/View"
          - "View/Read"
          - "Metrics/HealthCheck"
        - entries:
          - group: "ServiceUser"
          name: "ServiceUser"
          pattern: ".*"
          permissions:
          - "Job/ExtendedRead"
          - "Job/Delete"
          - "Job/Create"
          - "Job/Discover"
          - "Job/Read"
          - "Agent/Build"
          - "Job/Configure"
        - entries:
          - group: "authenticated"
          name: "User"
          pattern: ".*"
          permissions:
          - "Overall/Read"
        items:
        - entries:
          - group: "JobManager"
          name: "JobManager"
          pattern: "(?!^seedJobs$)(^.*$)"
          permissions:
          - "Job/Cancel"
          - "Job/Build"
          - "Job/Discover"
          - "Job/Read"
          - "View/Read"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy:
    roleBased:
      forceExistingJobs: false
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    mock:
      data: |-
        admin FullAdmin
        bob JobAdmin
        bill JobAdmin
        tim JobManager
        tom JobManager
        auto ServiceUser
        jane User
        john User
      groupIdStrategy: "caseInsensitive"
      randomDelay: false
      userIdStrategy: "caseInsensitive"
  slaveAgentPort: -1
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  pipelineGraphView:
    showGraphOnBuildPage: true
    showGraphOnJobPage: false
  prism:
    theme: PRISM
  themeManager:
    disableUserThemes: false
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy:
          specificUsersAuthorizationStrategy:
            userid: "auto"
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  globalLibraries:
    libraries:
    - defaultVersion: "main"
      name: "utils"
      retriever:
        modernSCM:
          libraryPath: "shared_libraries/utils/"
          scm:
            git:
              id: "6fc87cf5-d8df-492e-9773-786c0e84c7c7"
              remote: "https://github.com/Minreaux/jenkins-test"
              traits:
              - sparseCheckoutPaths:
                  extension:
                    sparseCheckoutPaths:
                    - path: "shared_libraries/utils/"
  hashicorpVault:
    configuration:
      disableChildPoliciesOverride: false
      engineVersion: "${CASC_VAULT_ENGINE_VERSION}"
      skipSslVerification: true
      timeout: 60
      vaultCredentialId: "vault-jenkins-role"
      vaultUrl: "${CASC_VAULT_URL}"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
tool:
  git:
    installations:
    - home: "git.exe"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
