# Plugin Installation Manager Tool for Jenkins list of plugins to install
# Plugin dependencies are handled automatically by the tool
plugins:
  - artifactId: configuration-as-code
    source:
      version: latest
  - artifactId: dark-theme
    source:
      version: latest
  - artifactId: git
    source:
      version: latest
  - artifactId: mock-security-realm
    source:
      version: latest
  - artifactId: workflow-aggregator # AKA Pipeline plugin
    source:
      version: latest
  - artifactId: pipeline-graph-view
    source:
      version: latest
  - artifactId: pipeline-stage-view
    source:
      version: latest
  - artifactId: role-strategy
    source:
      version: latest
