// Job DSL Groovy script that defines the job configuration for the testMultibranch Jenkins pipeline
multibranchPipelineJob('testMultibranch')
{
    branchSources
    {
        branchSource
        {
            source
            {
                fromScm
                {
                    name('setup-job-dsl')

                    scm
                    {
                        gitSCM
                        {
                            userRemoteConfigs
                            {
                                userRemoteConfig
                                {
                                    credentialsId('')
                                    name('jenkins-test')
                                    refspec('')
                                    url('https://github.com/Minreaux/jenkins-test.git')
                                }
                            }

                            branches
                            {
                                branchSpec
                                {
                                    name('setup-job-dsl')
                                }
                            }

                            extensions
                            {
                                sparseCheckoutPaths
                                {
                                    sparseCheckoutPaths
                                    {
                                        sparseCheckoutPath
                                        {
                                            path('jenkinsfiles/testMultibranch')
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    factory
    {
        workflowBranchProjectFactory
        {
            scriptPath('jenkinsfiles/testMultibranch')
        }
    }
}
