name: Jenkinsfile Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  jenkinsfile-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0

    - name: Setup Node.js
      uses: actions/setup-node@v5.0.0
      with:
        node-version: '20'

    - name: Install npm-groovy-lint
      run: npm install -g npm-groovy-lint

    - name: Lint Jenkinsfiles
      run: |
        echo "Linting Jenkinsfiles..."

        # Create a comprehensive file list and lint all at once
        groovy_files=$(find jenkinsfiles shared_libraries configs/job_dsl -name "*.groovy")
        extensionless_files=$(find jenkinsfiles -type f ! -name "*.*")
        
        if [ -n "$groovy_files" ]; then
          echo "Linting .groovy files..."
          groovy_list=$(echo "$groovy_files" | tr '\n' ',')
          npm-groovy-lint --files "$groovy_list" --failon error
        fi
        
        if [ -n "$extensionless_files" ]; then
          echo "Linting extensionless Jenkinsfiles..."
          for file in $extensionless_files; do
            npm-groovy-lint --files "$file" --source groovy --failon error
          done
        fi
        
        if [ -z "$groovy_files" ] && [ -z "$extensionless_files" ]; then
          echo "No files found to lint"
        fi
