name: Jenkinsfile Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  jenkinsfile-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0

    - name: Setup Node.js
      uses: actions/setup-node@v5.0.0
      with:
        node-version: '20'

    - name: Install npm-groovy-lint
      run: npm install -g npm-groovy-lint

    - name: Lint Jenkinsfiles
      run: |
        echo "Linting Jenkinsfiles..."

        # Create a comprehensive file list and lint all at once
        files=$(find jenkinsfiles -type f \( -name "*.groovy" -o ! -name "*.*" \); find shared_libraries -name "*.groovy"; find configs/job_dsl -name "*.groovy")
        if [ -n "$files" ]; then
          file_list=$(echo "$files" | tr '\n' ',')
          npm-groovy-lint --files "$file_list" --failon error
        else
          echo "No files found to lint"
        fi
